import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { freshState } from '../public/pet-state.js';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const base = (process.env.BASE_URL || 'http://localhost:8789').replace(/\/$/, '');
const output = new URL('../test-results/dojo/', import.meta.url);
await mkdir(output, { recursive: true });
const screenshot = name => new URL(name, output).pathname;
const browser = await chromium.launch({ headless: true });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 375, height: 812 } });
  const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
  await page.route('**/dojo-test', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/characters.css"></head><body><button id="original">基地入口</button></body></html>' }));
  await page.goto(`${base}/dojo-test`);
  await page.clock.install();
  await page.evaluate(async () => { document.querySelector('#original').focus(); const { openDefenseDojo } = await import('/defense-dojo.js'); window.closeCount = 0; window.dojo = openDefenseDojo({ onClose: () => window.closeCount++ }); });
  await page.locator('.dojo-dialog').screenshot({ path: screenshot('mobile-ready.png') });
  const noOverflow = () => page.evaluate(() => { const dialog = document.querySelector('.dojo-dialog'); return dialog.scrollWidth <= dialog.clientWidth; });
  assert.equal(await noOverflow(), true);
  await page.click('[data-dojo="start"]');
  await page.clock.runFor(1750);
  assert.equal(await page.locator('.dojo-stage').getAttribute('data-phase'), 'warning');
  await page.keyboard.press('4');
  assert.equal(await page.locator('.dojo-stage .hero-actor').getAttribute('data-pose'), 'defend');
  assert.equal(await page.locator('.hero-defense-arms').evaluate(el => getComputedStyle(el).visibility), 'visible');
  await page.locator('.dojo-dialog').screenshot({ path: screenshot('mobile-x-defense.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.dojo-dialog').getAttribute('data-paused'), 'true');
  const frozen = await page.locator('.dojo-countdown').textContent();
  await page.clock.runFor(6000);
  assert.equal(await page.locator('.dojo-countdown').textContent(), frozen);
  await page.click('[data-dojo="resume"]');
  await page.clock.runFor(2800);
  assert.equal(await page.locator('[data-round="0"]').getAttribute('data-state'), 'blocked');
  await page.clock.runFor(4000);
  assert.equal(await page.locator('.dojo-stage').getAttribute('data-phase'), 'warning');
  // Leave the second round undefended, then enter round three's live warning.
  await page.clock.runFor(5000);
  assert.equal(await page.locator('[data-round="1"]').getAttribute('data-state'), 'missed');
  for (let tick = 0; tick < 20 && await page.locator('.dojo-stage').getAttribute('data-phase') === 'prepare'; tick++) await page.clock.runFor(100);
  assert.equal(await page.locator('.dojo-stage').getAttribute('data-phase'), 'warning');
  const remaining = Number((await page.locator('.dojo-countdown').textContent()).replace('s', '')) * 1000;
  await page.clock.runFor(Math.max(0, remaining - 180));
  assert.equal(await page.locator('.dojo-stage').getAttribute('data-perfect'), 'true');
  await page.keyboard.press('Space');
  await page.clock.runFor(2300);
  assert.equal(await page.locator('[data-round="2"]').getAttribute('data-state'), 'perfect');
  assert.equal(await page.locator('.dojo-summary').isVisible(), true);
  assert.match(await page.locator('.dojo-score').textContent(), /2/);
  assert.equal(await noOverflow(), true);
  await page.locator('.dojo-dialog').screenshot({ path: screenshot('mobile-result.png') });
  await page.click('[data-dojo="restart"]');
  await page.clock.runFor(2000);
  const beforeStall = Number((await page.locator('.dojo-countdown').textContent()).replace('s', ''));
  await page.clock.fastForward(5000);
  assert.equal(await page.locator('.dojo-dialog').getAttribute('data-paused'), 'true');
  assert.ok(Math.abs(Number((await page.locator('.dojo-countdown').textContent()).replace('s', '')) - beforeStall) < 0.1);
  assert.match(await page.locator('.dojo-pause-reason').textContent(), /停顿/);
  await page.click('[data-dojo="resume"]');
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); });
  assert.equal(await page.locator('.dojo-dialog').getAttribute('data-paused'), 'true');
  const hiddenTime = await page.locator('.dojo-countdown').textContent();
  await page.clock.runFor(10000);
  assert.equal(await page.locator('.dojo-countdown').textContent(), hiddenTime);
  await page.evaluate(() => { delete document.hidden; document.dispatchEvent(new Event('visibilitychange')); });
  assert.equal(await page.locator('.dojo-dialog').getAttribute('data-paused'), 'true');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.dojo-dialog').count(), 0);
  assert.equal(await page.evaluate(() => window.closeCount), 1);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'original');
  await page.evaluate(() => window.dojo.dispose());
  assert.equal(await page.evaluate(() => window.closeCount), 1);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 1280, height: 950 });
  await page.evaluate(async () => { window.dojo = (await import('/defense-dojo.js')).openDefenseDojo(); });
  await page.click('[data-dojo="start"]'); await page.clock.runFor(1800); await page.click('[data-dojo="defend"]');
  assert.equal(await page.locator('.hero-defense-arms').evaluate(el => getComputedStyle(el).visibility), 'visible');
  assert.equal(await noOverflow(), true);
  await page.locator('.dojo-dialog').screenshot({ path: screenshot('desktop-reduced-motion.png') });
  await context.close();

  // Real application entry and real API: three successful practice blocks must
  // leave growth, real-combat achievements and the server revision untouched.
  const appContext = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
  const seed = { ...freshState(), xp: 220, stars: 75, wins: 2, blocks: 3, fed: 2, training: 4, milestones: ['first_meal'], food: 90, energy: 95 };
  await appContext.addInitScript(value => localStorage.setItem('aoteman-pet-v2', JSON.stringify(value)), seed);
  const app = await appContext.newPage();
  app.on('pageerror', error => errors.push(error.message));
  await app.goto(base);
  await app.waitForFunction(() => !document.getElementById('feedBtn').disabled);
  await app.locator('#saveStatus[data-status="synced"]').waitFor({ state: 'attached', timeout: 20000 });
  const local = () => app.evaluate(() => JSON.parse(localStorage.getItem('aoteman-pet-v2')));
  const code = await app.evaluate(() => JSON.parse(localStorage.getItem('aoteman-cloud-v1')).recoveryCode);
  const head = async () => {
    const response = await fetch(`${base}/api/v1/save`, { headers: { Authorization: `Bearer ${code}` } });
    assert.equal(response.status, 200);
    return response.json();
  };
  const growth = state => Object.fromEntries(['xp', 'stars', 'wins', 'blocks', 'milestones', 'fed', 'training', 'pats'].map(key => [key, state[key]]));
  const beforeLocal = growth(await local());
  const beforeServer = await head();
  assert.deepEqual(beforeLocal, growth(seed));
  const writes = [];
  app.on('request', request => {
    const url = new URL(request.url());
    if (url.pathname.startsWith('/api/v1/') && ['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method())) writes.push(`${request.method()} ${url.pathname}`);
  });
  await app.click('#defendBtn');
  await app.locator('.dojo-dialog').waitFor();
  assert.equal(await app.locator('#feedBtn').isDisabled(), true);
  assert.equal(await app.locator('#trainBtn').isDisabled(), true);
  assert.equal(await app.locator('#restBtn').isDisabled(), true);
  await app.click('[data-dojo="start"]');
  for (let round = 0; round < 3; round++) {
    await app.waitForFunction(index => document.querySelector(`[data-round="${index}"]`)?.dataset.state === 'current' && document.querySelector('.dojo-stage')?.dataset.phase === 'warning', round, { timeout: 12000 });
    await app.click('[data-dojo="defend"]');
    assert.equal(await app.locator('.dojo-stage .hero-actor').getAttribute('data-pose'), 'defend');
    await app.waitForFunction(index => ['blocked', 'perfect'].includes(document.querySelector(`[data-round="${index}"]`)?.dataset.state), round, { timeout: 7000 });
  }
  await app.locator('.dojo-summary').waitFor();
  assert.equal(await app.locator('.dojo-score strong').textContent(), '3/ 3');
  await app.locator('.dojo-dialog').screenshot({ path: screenshot('app-three-blocks.png') });
  await app.locator('.dojo-summary [data-dojo="close"]').click();
  await app.locator('.dojo-dialog').waitFor({ state: 'detached' });
  await app.waitForFunction(() => !document.getElementById('feedBtn').disabled);
  for (const selector of ['#trainBtn', '#restBtn', '#defendBtn']) assert.equal(await app.locator(selector).isDisabled(), false);
  assert.equal(await app.evaluate(() => document.activeElement.id), 'defendBtn');
  // Observe longer than the save debounce, then inspect the actual API head.
  await app.waitForTimeout(1600);
  assert.deepEqual(growth(await local()), beforeLocal);
  const afterServer = await head();
  assert.deepEqual(growth(afterServer.state), growth(beforeServer.state));
  assert.equal(afterServer.revision, beforeServer.revision);
  assert.deepEqual(writes, [], 'Free practice must not enqueue reward or achievement writes');
  await appContext.close();
  assert.deepEqual(errors, []);
  console.log('PASS: dojo mobile/desktop, X animation, all three outcomes, pause/background/stall freeze, retry, reduced motion, focus/disposal; real app three-round completion unlocks care and leaves local/API growth and server revision unchanged.');
} finally { await browser.close(); }
